<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
	<!-- FIXED MSB3823 -->
	<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <OutputType>WinExe</OutputType>
    <StartupObject>DBZ_LotSS_Editor.My.MyApplication</StartupObject>
    <RootNamespace>DBZ_LotSS_Editor</RootNamespace>
    <MyType>WindowsForms</MyType>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.vb</DefaultItemExcludes>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
	<EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	<!-- Assembly Metadata -->
	<Title>DBZ LotSS Editor</Title>
	<Description>An all purpose Editor for the SNES Game Dragonball Z: Legend of the Super Saiyan. Built using C# and .NET framework.</Description>
	<Company>Cetra Games</Company>
	<Product>DragonBall Z: Legend of the Super Saiyan Editor</Product>
	<Copyright>Copyright © 2014 by Cetra Games</Copyright>
	<!-- Versioning -->
	<Version>0.79.0</Version>
	<AssemblyVersion>0.79.0</AssemblyVersion>
	<FileVersion>0.79.0</FileVersion>
	<!-- COM and Interop Settings -->
	<ComVisible>false</ComVisible>
	<Guid>ecd18392-9589-413a-8747-aa12ee3f6924</Guid>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\DBZ LotSS Editor.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\DBZ LotSS Editor.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <OptionExplicit>On</OptionExplicit>
  </PropertyGroup>
  <PropertyGroup>
    <OptionCompare>Binary</OptionCompare>
  </PropertyGroup>
  <PropertyGroup>
    <OptionStrict>Off</OptionStrict>
  </PropertyGroup>
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Resources\DBZ LotSS Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.Design" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="Microsoft.VisualBasic" />
    <Import Include="System" />
    <Import Include="System.Collections" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Diagnostics" />
    <Import Include="System.Windows.Forms" />
    <Import Include="System.Linq" />
    <Import Include="System.Xml.Linq" />
    <Import Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Data_Skills.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Data_Global.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Data_Groups.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Palette_System.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Palette_Characters.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Palette_Flyers.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Sprite_Flyers.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sprite_System.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sprite_Characters.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sprite_Control.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Text_Descriptions.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Text_Skills.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Text_Items.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Text_Characters.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Text_Battlers.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Text_Dialogues.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Data_Items.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Data_Maps.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Data_Dialogues.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Data_Characters.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sprite_Portrait.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Palette_Portrait.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Palette_Battlers.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sprite_Battlers.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Data_Battlers.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.cs</LastGenOutput>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\PaletteEditor_System.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SpriteEditor_Flyers.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SpriteEditor_System.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SpriteEditor_Characters.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SpriteEditor_Battlers.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\DataEditor_Characters.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TextEditor_Dialogues.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TextEditor_Descriptions.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TextEditor_Items.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TextEditor_Characters.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TextEditor_Battlers.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\PaletteEditor_Flyers.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\PaletteEditor_Battlers.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\PaletteEditor_Characters.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\PaletteEditor_Portraits.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\FontTable.tbl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\SpriteEditor_Portraits.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TextEditor_Skills.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.7.1">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.7.1 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
	<ItemGroup>
		<!-- 1. Local Development Mode: Used on your PC where the folder exists -->
		<ProjectReference Include="..\..\Reverse-Engineering-Toolkit\BasicTools\BasicTools.csproj" Condition="Exists('..\..\Reverse-Engineering-Toolkit\BasicTools\BasicTools.csproj')" />
		<ProjectReference Include="..\..\Reverse-Engineering-Toolkit\HexTools\HexTools.csproj" Condition="Exists('..\..\Reverse-Engineering-Toolkit\HexTools\HexTools.csproj')" />

		<!-- 2. Cloud Server Build Mode: Used on GitHub where the toolkit folder is absent -->
		<PackageReference Include="ReverseEngineeringToolkit.BasicTools" Version="0.8.0.0" Condition="!Exists('..\..\Reverse-Engineering-Toolkit\BasicTools\BasicTools.csproj')" />
		<PackageReference Include="ReverseEngineeringToolkit.HexTools" Version="0.8.0.0" Condition="!Exists('..\..\Reverse-Engineering-Toolkit\HexTools\HexTools.csproj')" />
	</ItemGroup>
  <ItemGroup>
    <Content Include="Documents\Notes.txt" />
    <Content Include="Documents\Offsets.txt" />
  </ItemGroup>
  <ItemGroup>
	  <!-- Explicitly forces the compiler to build the missing Trademark attribute -->
	  <AssemblyAttribute Include="System.Reflection.AssemblyTrademarkAttribute">
	    <_Parameter1>MakoInfused / Dino Suvalic</_Parameter1>
	  </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>